package model;
// Generated 26.Ağu.2019 09:08:06 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "customer")
public class Customer implements java.io.Serializable {

	private Integer cid;
	private String cname;
	private String cmail;
	private String cpassword;
	private String cphone;
	private String caddress;
	
	public Customer() {
	}

	public Customer(String cname, String cmail, String cpassword, String cphone, String caddress) {
		this.cname = cname;
		this.cmail = cmail;
		this.cpassword = cpassword;
		this.cphone = cphone; 
		this.caddress = caddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cid", unique = true, nullable = false)
	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	@Column(name = "cname", nullable = false)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Column(name = "cmail", nullable = false)
	public String getCmail() {
		return this.cmail;
	}

	public void setCmail(String cmail) {
		this.cmail = cmail;
	}
	
	@Column(name = "cpassword", nullable = false)
	public String getCpassword() {
		return this.cpassword;
	}

	public void setCpassword(String cpassword) {
		this.cpassword = cpassword;
	}

	@Column(name = "cphone", nullable = false)
	public String getCphone() {
		return this.cphone;
	}

	public void setCphone(String cphone) {
		this.cphone = cphone;
	}
	
	@Column(name = "caddress", nullable = false)
	public String getCaddress() {
		return this.caddress;
	}

	public void setCaddress(String caddress) {
		this.caddress = caddress;
	}

}
